### ISSUE TITLE
App doesn't close if device is not FYT

### ISSUE THREAD

**Issue by marjanoos** [hvdwolf/FET#4]
When installed and opened on Android phone, app detects that devices is not FYT and modal with text "This is not a FYT unit. The app will be closed.". But App closes only when user clicks "OK". If user clicks outside a modal, modal is closed and app is still opened.

**Preconditions:**
App in version 1.2.2 is installed on any device with Android system which isn't FYT

**Steps to reproduce:**
1. Open the App from drawer
2. When the modal is displayed with text "This is not a FYT unit..", touch the screen outside this modal

**Expected result:**
App is closed

**Current result:**
App stays open

**Comment by hvdwolf** [comment]
You are right. Part of the code is simply missing. The application should close automatically after 2500 milliseconds (2.5 seconds), but that part has disappeared.

I just added it again.

**Comment by hvdwolf** [comment]
I changed the delay time to 3500 milliseconds by the way, to give a user a slighly  longer disappointing look at it ;)
